services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../frontend:/usr/share/nginx/html

  app:
    image: eclipse-temurin:17
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ../backend/camagru:/app
    command: java -jar target/camagru-1.0-SNAPSHOT.jar
    # Install Maven and any other required packages, build the project, then run the application
    entrypoint: |
      sh -c "apt-get update && apt-get install -y ffmpeg maven && mvn clean package && java -jar target/camagru-1.0-SNAPSHOT.jar"
